//src/routes/appRoutes.js
export const appRoutes = {
  tablas:               "/tablas",
  bodega:               "/tablas/bodegas",
  categoria:            "/tablas/categorias",
  destinatario:         "/tablas/destinatarios",
  existencia:           "/tablas/existencias",
  lote:                 "/tablas/lotes",
  marca:                "/tablas/marcas",
  movimiento:           "/tablas/movimientos",
  detalleMovimiento:    "/tablas/detalle_movimientos",
  precioProducto:       "/tablas/precio_productos",
  presentacion:         "/tablas/presentaciones",
  producto:             "/tablas/productos",
  proveedor:            "/tablas/proveedores",
  productoProveedor:    "/tablas/producto_proveedores",
  tipoDocumento:        "/tablas/tipo_documentos",
  uMedida:              "/tablas/unidad_medidas",
  panel:                "/panel",
  inventarioInicial:    "/panel/inventario_inicial",
  compra:               "/panel/compra",
  venta:                "/panel/venta",
  ajusteContable:       "/panel/ajuste_contable",
  devolucion:           "/panel/devolucion",
  consumoInterno:       "/panel/consumo_interno",
  produccion:           "/panel/produccion",
  usoenproducción:      "/panel/usoenproducción",
  merma:                "/panel/merma",
  vencimiento:          "/panel/vencimiento",
  descarte:             "/panel/descarte",
  donaciónrecibida:     "/panel/donaciónrecibida",
  donaciónentregada:    "/panel/donaciónentregada",
  regularizacióncontable:      "/panel/regularizacióncontable",
  transferenciaentrealmacenes: "/panel/transferenciaentrealmacenes",
  cambiodeubicación:    "/panel/cambiodeubicación",
  reempaque_reetiquetado:      "/panel/reempaque_reetiquetado",
  cambiodepresentación: "/panel/cambiodepresentación",
  reservadestock:       "/panel/reservadestock",
  cuarentena_bloqueo:   "/panel/cuarentena_bloqueo",
  liberacióndebloqueo:  "/panel/liberacióndebloqueo",
  préstamorecibido:     "/panel/préstamorecibido",
  préstamoentregado:    "/panel/préstamoentregado",
  anulacióndecompra:    "/panel/anulacióndecompra",
  anulacióndeventa:     "/panel/anulacióndeventa",
  controldecalidad:     "/panel/controldecalidad",
  ajusteadministrativo: "/panel/ajusteadministrativo",

};




